require 'harmony/pitch'
require 'harmony/pitch_class'
require 'harmony/interval'
require 'harmony/interval_class'
require 'harmony/vector'
require 'harmony/vector/pitch'
require 'harmony/vector/interval'
require 'harmony/set_comparison_coercions'
require 'harmony/pitch_set'
require 'harmony/pitch_set/modulo_octaves'
require 'harmony/pitch_set/modulo_transposition'
require 'harmony/pitch_class_set'
require 'harmony/pitch_class_set/modulo_octaves'
require 'harmony/pitch_class_set/modulo_transposition'

include Harmony
